name: Job Concurrency Checker
on: [pull_request]

## Cancel concurrent workflow run to avoid wasting minutes
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  IsConcurrency:
    runs-on: shared
    steps:
      - run: true
