name: Quality Gate

on:
  pull_request:
    branches: [ "main" ]

env:
  NO_PROXY: ${{ secrets.OLX_NEXUS_NO_PROXY }}
  HTTP_PROXY: ${{ secrets.OLX_NEXUS_PROXY }}

jobs:
  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Quality Gate Action
        uses: olxbr/quality-gate-action@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
