name: Quality Gate

on:
  pull_request:
    branches: [ "main" ]

jobs:
  quality-gate:
    name: Quality Gate
    runs-on: [self-hosted, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Quality Gate Action
        uses: olxbr/quality-gate-action@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          docs_url: "https://olxbr.atlassian.net/l/cp/vQZeDHDM"
